# Generated by Django 3.2.12 on 2023-12-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mythId', models.CharField(max_length=500)),
                ('mythDesc', models.CharField(max_length=1000)),
                ('factDesc', models.CharField(max_length=1000)),
                ('source', models.CharField(max_length=100)),
            ],
        ),
    ]
