# Generated by Django 3.2.12 on 2023-12-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpabbyapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myths',
            name='id',
        ),
        migrations.AlterField(
            model_name='myths',
            name='mythId',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
