# Generated by Django 3.2.12 on 2023-12-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpabbyapi', '0002_auto_20231228_1001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myths',
        ),
    ]
