# Generated by Django 5.0 on 2023-12-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpabbyapi', '0004_food_myth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myth',
            name='source',
            field=models.CharField(max_length=1000),
        ),
    ]
