# Generated by Django 3.2.12 on 2024-01-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpabbyapi', '0005_alter_myth_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(default='N/A', max_length=1000),
        ),
    ]
