# Generated by Django 5.0.1 on 2024-03-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpabbyapi', '0006_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='foodName',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
