# Generated by Django 5.0.1 on 2024-03-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpabbyapi', '0007_alter_food_foodname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myth',
            name='mythDesc',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
